[package]
name = "algorithms"
version = "0.1.0"
authors = ["ichyo <ichyo00@gmail.com>"]
edition = "2018"
repository = "https://github.com/ichyo/algorithms"
readme = "README.md"
description = "a collection of classic algorithms for programming contests"
