name: Verify

on: [push]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip install -r system-test/requirements.txt

      - name: Run verification
        run: system-test/run.sh
